### ISSUE TITLE
No such file or directory: './Encoder_lr_scheduler_ckpt'

### ISSUE THREAD

**Issue by Gaturae** [tianyu0207/IGD#2]
No such file or directory: './Encoder_lr_scheduler_ckpt'

**Comment by YossiZhao** [comment]
> No such file or directory: './Encoder_lr_scheduler_ckpt'

I also meet same error, I don't know how to get ckpt when I first run the program. Did you solve the problem?

**Comment by tianyu0207** [comment]
> No such file or directory: './Encoder_lr_scheduler_ckpt'

Hi The model is pre-trained based on the distillation of Imagenet. We will update the checkpoints shortly.

**Comment by cyh-0** [comment]
Hi, I have updated the pre-trained weight for KD and I have changed the file name to "Encoder_KD_ckpt"
