### ISSUE TITLE
about  Hyper-Kvasir dataset

### ISSUE THREAD

**Issue by YapengTeng** [tianyu0207/IGD#6]

**Comment by tianyu0207** [comment]
You need to just to select the lower GI files from their official dataset link.
 
There are these folders that show normal bowel
 
1. Anatomical-landmarks/cecum - Caecum is the start of the large bowel (start meaning the direction poo is flowing)
2. Anatomical-landmarks/ileum - Ileum is the small bowel that connects to the caecum which is also another indication that the colonoscope as reached the end and is ready to be pulled out slowly and surface examined carefully
3. Quality-of-mucosal-views/bbps-2-3 - This has normal bowel pictures from random places in the bowel. Any abnormal things that is seen in it is just poo or food particulate
4. Quality-of-mucosal-views/bbps-2-3 (in labeled-videos) - Also can be used.
 
bbps stands for Boston Bowel Preparation Scale. 0 means terrible prep and progressive better to 3 which means perfect clean bowel
bbps-0-1 are images with way too much poo that obscures colonic views.

Hope this can help you to select the dataset
